---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    # We are running the command line argument to the container to create this /tmp/healty file 
    # And then remove it after the 30 seconds and this removal of file would trigger a probe failure
    args: 
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rvf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      # initialDelaySeconds parameter requests the kubelet to wait for 3 seconds before the first probe. 
      initialDelaySeconds: 3 
      
      # failureThreshold parameter set to 1 instructs kubelet to declare the container unhealthy,
      # after single probe failure and trigger a container to restart as a result.
      failureThreshold: 1 
      
      # the existance of the /tmp/healthy file is configured to be checked every 5 seconds using this parameter. 
      periodSeconds: 5    
